sudo: required
services:
  - docker

before_install:
  - docker build -t llouis03/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true llouis03/docker-test npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-529788924674"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  
  Docker-env.hzhtdcgfp5.us-east-2.elasticbeanstalk.com